module.exports = `
    extend type Query {
        # getStudies(limit: Int, continueFromID: String, filter: String, offset: Int, sortField: String, sortDirection: String, columnFilters: [TableColumnFilter!]): [study]
        getAllStudies(limit: Int, continueFromID: String, filter: String, offset: Int, sortField: String, sortDirection: String, columnFilters: [TableColumnFilter!]): [study]
        getStudyPatientTable(limit: Int, continueFromID: String, filter: String, offset: Int, sortField: String, sortDirection: String, columnFilters: [TableColumnFilter!]): [studyPatientTableRow]
        
    }
    type study {
        studyID: String
        status: String
        type: String
        organisationFull: String
        studyPatients: [spat]
        organisationShort: String
        permission: String
        shortname: String
        eudract: String
        start: Float
        phase: String
        firstPatInPlanned: Float
        _id: String
    }
  type spat {
    patID: String
    recruitmentDate: Float
  }
  type studyPatientTableRow {
    _id: String
    studyID: String
    shortname: String
    patID: String
    recruitmentDate: Float
  }
`
