import { writable } from 'svelte/store';

export const maxStore = writable({
    maximizeBioMaterialChart: false,
    maximizeBioMaterialTable: false,
    maximizePatientCohortAgeChart: false,
    maximizePatientCohortDeathChart: false,
    maximizePatientCohortGenderChart: false,
    maximizePatientCohortMapChart: false,
    maximizePatientCohortOverviewTable: false,
    maximizePatientCohortHistoryTable: false,
    maximizePatientCohortPatientTable: false,
    maximizeDiagnosisBarChart: false,
    maximizeDiagnosisDiagnosticTable: false,
    maximizeDiagnosisHistologyTable: false,
    maximizeConsultationChart: false,
    maximizeConsultationTable: false,
    maximizeConsultationTimeChart: false,
    maximizePatientSingleDiagnosisMap: false,
    maximizePatientSingleEventChart: false,
    maximizePatientSingleHistoryTable: false,
    maximizePatientSingleMetastasisMap: false,
    maximizeProgressChart: false,
    maximizeProgressTable: false,
    maximizeProgressTimeChart: false,
    maximizeStatusChart: false,
    maximizeStatusTable: false,
    maximizeStatusTimeChart: false,
    maximizeStatusOtherChart: false,
    maximizeStudyChart: false,
    maximizeStudyOverviewTable: false,
    maximizeStudyPatientChart: false,
    maximizeStudyPatientTable: false,
    maximizeSupplementaryChart: false,
    maximizeSupplementaryTable: false,
    maximizeMolecularMarkerChart: false,
    maximizeMolecularMarkerTable: false,
    maximizeSurvivalFollowUpAssessment: false,
    maximizeSurvivalKaplanMeierChart: false,
    maximizeSurvivalCoxRegression: false,
    maximizeTherapyOpsSubstanceTable: false,
    maximizeTherapyGeneralChart: false,
    maximizeTherapyGeneralTable: false,
    maximizeTherapyGeneralTimeChart: false,
    maximizeTherapyGeneralComplicationChart: false,
    maximizeTherapyOperationChart: false,
    maximizeTherapyOperationTable: false,
    maximizeTherapyOperationOpsCategoryTable: false,
    maximizeTherapyOperationOpsCodeTable: false,
    maximizeTherapyRadiationChart: false,
    maximizeTherapyRadiationTable: false,
    maximizeTherapyRadiationMap: false,
    maximizeTherapySystemicChart: false,
    maximizeTherapySystemicTable: false,
    maximizeTherapySystemicSubstanceTable: false,
    maximizeTNM3DChart: false,
    maximizeTNMMetastasisTable: false,
    maximizeTNMBodyMap: false,
    maximizeTNMOverviewTable: false,
    maximizeTNMChart: false,
    maximizeTumorboardChart: false,
    maximizeTumorboardTable: false,
    maximizeTumorboardTimeChart: false,
    maximizeTumorboardOtherChart: false,
    maximizeTherapyChart : false,
    maximizeTherapyTable : false,
    maximizeTherapyTimeChart : false,
    maximizeTherapyOpsSubstanceTables : false
});