export const ccode = {
	AFG: 'Afghanistan',
	ALA: 'Åland Islands',
	ALB: 'Albania',
	DZA: 'Algeria',
	ASM: 'American Samoa',
	AND: 'Andorra',
	AGO: 'Angola',
	AIA: 'Anguilla',
	ATA: 'Antarctica',
	ATG: 'Antigua and Barbuda',
	ARG: 'Argentina',
	ARM: 'Armenia',
	ABW: 'Aruba',
	AUS: 'Australia',
	AUT: 'Austria',
	AZE: 'Azerbaijan',
	BHS: 'Bahamas',
	BHR: 'Bahrain',
	BGD: 'Bangladesh',
	BRB: 'Barbados',
	BLR: 'Belarus',
	BEL: 'Belgium',
	BLZ: 'Belize',
	BEN: 'Benin',
	BMU: 'Bermuda',
	BTN: 'Bhutan',
	BOL: 'Bolivia',
	BES: 'Bonaire',
	BIH: 'Bosnia and Herzegovina',
	BWA: 'Botswana',
	BVT: 'Bouvet Island',
	BRA: 'Brazil',
	IOT: 'British Indian Ocean Territory',
	BRN: 'Brunei Darussalam',
	BRN: 'Brunei',
	BGR: 'Bulgaria',
	BFA: 'Burkina Faso',
	MMR: 'Burma',
	BDI: 'Burundi',
	KHM: 'Cambodia',
	CMR: 'Cameroon',
	CAN: 'Canada',
	CPV: 'Cape Verde',
	CYM: 'Cayman Islands',
	CAF: 'Central African Republic',
	TCD: 'Chad',
	CHL: 'Chile',
	CHN: 'China',
	CXR: 'Christmas Island',
	CCK: 'Cocos (Keeling) Islands',
	COL: 'Colombia',
	COM: 'Comoros',
	COG: 'Congo',
	COD: 'Congo,  Democratic Republic of the',
	COK: 'Cook Islands',
	CRI: 'Costa Rica',
	CIV: "Côte d'Ivoire",
	HRV: 'Croatia',
	CUB: 'Cuba',
	CUW: 'Curaçao',
	CYP: 'Cyprus',
	CZE: 'Czech Republic',
	DNK: 'Denmark',
	DJI: 'Djibouti',
	DMA: 'Dominica',
	DOM: 'Dominican Republic',
	ECU: 'Ecuador',
	EGY: 'Egypt',
	SLV: 'El Salvador',
	GNQ: 'Equatorial Guinea',
	ERI: 'Eritrea',
	EST: 'Estonia',
	ETH: 'Ethiopia',
	FLK: 'Falkland Islands (Malvinas)',
	FRO: 'Faroe Islands',
	FJI: 'Fiji',
	FIN: 'Finland',
	FRA: 'France',
	GUF: 'French Guiana',
	PYF: 'French Polynesia',
	ATF: 'French Southern Territories',
	GAB: 'Gabon',
	GMB: 'Gambia',
	GEO: 'Georgia',
	DEU: 'Germany',
	GHA: 'Ghana',
	GIB: 'Gibraltar',
	GRC: 'Greece',
	GRL: 'Greenland',
	GRD: 'Grenada',
	GLP: 'Guadeloupe',
	GUM: 'Guam',
	GTM: 'Guatemala',
	GGY: 'Guernsey',
	GNB: 'Guinea-Bissau',
	GIN: 'Guinea',
	GUY: 'Guyana',
	HTI: 'Haiti',
	HMD: 'Heard Island and McDonald Islands',
	VAT: 'Holy See (Vatican City State)',
	HND: 'Honduras',
	HKG: 'Hong Kong',
	HUN: 'Hungary',
	ISL: 'Iceland',
	IND: 'India',
	IDN: 'Indonesia',
	IRN: 'Iran, Islamic Republic of',
	IRQ: 'Iraq',
	IRL: 'Ireland',
	IMN: 'Isle of Man',
	ISR: 'Israel',
	ITA: 'Italy',
	CIV: 'Ivory Coast',
	JAM: 'Jamaica',
	JPN: 'Japan',
	JEY: 'Jersey',
	JOR: 'Jordan',
	KAZ: 'Kazakhstan',
	KEN: 'Kenya',
	KIR: 'Kiribati',
	PRK: "Korea, Democratic People's Republic of",
	KOR: 'Korea, Republic of',
	XKX: 'Kosovo',
	KWT: 'Kuwait',
	KGZ: 'Kyrgyzstan',
	LAO: "Lao People's Democratic Republic",
	LVA: 'Latvia',
	LBN: 'Lebanon',
	LSO: 'Lesotho',
	LBR: 'Liberia',
	LBY: 'Libya',
	LBY: 'Libyan Arab Jamahiriya',
	LIE: 'Liechtenstein',
	LTU: 'Lithuania',
	LUX: 'Luxembourg',
	MAC: 'Macao',
	MKD: 'Macedonia, the former Yugoslav Republic of',
	MDG: 'Madagascar',
	MWI: 'Malawi',
	MYS: 'Malaysia',
	MDV: 'Maldives',
	MLI: 'Mali',
	MLT: 'Malta',
	MHL: 'Marshall Islands',
	MTQ: 'Martinique',
	MRT: 'Mauritania',
	MUS: 'Mauritius',
	MYT: 'Mayotte',
	MEX: 'Mexico',
	FSM: 'Micronesia, Federated States of',
	MDA: 'Moldova, Republic of',
	MCO: 'Monaco',
	MNG: 'Mongolia',
	MNE: 'Montenegro',
	MSR: 'Montserrat',
	MAR: 'Morocco',
	MOZ: 'Mozambique',
	MMR: 'Myanmar',
	NAM: 'Namibia',
	NRU: 'Nauru',
	NPL: 'Nepal',
	ANT: 'Netherlands Antilles',
	NLD: 'Netherlands',
	NCL: 'New Caledonia',
	NZL: 'New Zealand',
	NIC: 'Nicaragua',
	NER: 'Niger',
	NGA: 'Nigeria',
	NIU: 'Niue',
	NFK: 'Norfolk Island',
	MNP: 'Northern Mariana Islands',
	NOR: 'Norway',
	OMN: 'Oman',
	PAK: 'Pakistan',
	PLW: 'Palau',
	PSE: 'Palestinian Territory, Occupied',
	PAN: 'Panama',
	PNG: 'Papua New Guinea',
	PRY: 'Paraguay',
	PER: 'Peru',
	PHL: 'Philippines',
	PCN: 'Pitcairn',
	POL: 'Poland',
	PRT: 'Portugal',
	PRI: 'Puerto Rico',
	QAT: 'Qatar',
	REU: 'Réunion',
	ROU: 'Romania',
	RUS: 'Russia',
	RUS: 'Russian Federation',
	RWA: 'Rwanda',
	BLM: 'Saint-Barthélemy',
	SHN: 'Saint Helena, Ascension and Tristan da Cunha',
	KNA: 'Saint Kitts and Nevis',
	LCA: 'Saint Lucia',
	MAF: 'Saint Martin (French part)',
	SPM: 'Saint Pierre and Miquelon',
	VCT: 'Saint Vincent & the Grenadines',
	VCT: 'Saint Vincent and the Grenadines',
	WSM: 'Samoa',
	SMR: 'San Marino',
	STP: 'Sao Tome and Principe',
	SAU: 'Saudi Arabia',
	SEN: 'Senegal',
	SRB: 'Serbia',
	SYC: 'Seychelles',
	SLE: 'Sierra Leone',
	SGP: 'Singapore',
	SXM: 'Sint Maarten (Dutch part)',
	SVK: 'Slovakia',
	SVN: 'Slovenia',
	SLB: 'Solomon Islands',
	SOM: 'Somalia',
	ZAF: 'South Africa',
	SGS: 'South Georgia and the South Sandwich Islands',
	KR: 'South Korea',
	SSD: 'South Sudan',
	ESP: 'Spain',
	LKA: 'Sri Lanka',
	VCT: 'St. Vincent and the Grenadines',
	SDN: 'Sudan',
	SUR: 'Suriname',
	SJM: 'Svalbard and Jan Mayen',
	SWZ: 'Swaziland',
	SWE: 'Sweden',
	CHE: 'Switzerland',
	SYR: 'Syrian Arab Republic',
	TWN: 'Taiwan',
	TJK: 'Tajikistan',
	TZA: 'Tanzania, United Republic of',
	THA: 'Thailand',
	TLS: 'Timor-Leste',
	TGO: 'Togo',
	TKL: 'Tokelau',
	TON: 'Tonga',
	TTO: 'Trinidad and Tobago',
	TUN: 'Tunisia',
	TUR: 'Turkey',
	TKM: 'Turkmenistan',
	TCA: 'Turks and Caicos Islands',
	TUV: 'Tuvalu',
	UGA: 'Uganda',
	UKR: 'Ukraine',
	ARE: 'United Arab Emirates',
	GBR: 'United Kingdom',
	UMI: 'United States Minor Outlying Islands',
	USA: 'United States',
	URY: 'Uruguay',
	UZB: 'Uzbekistan',
	VUT: 'Vanuatu',
	VEN: 'Venezuela',
	VNM: 'Viet Nam',
	VNM: 'Vietnam',
	VGB: 'Virgin Islands, British',
	VIR: 'Virgin Islands, U.S.',
	WLF: 'Wallis and Futuna',
	ESH: 'Western Sahara',
	YEM: 'Yemen',
	ZMB: 'Zambia',
	ZWE: 'Zimbabwe',

	AF: 'Afghanistan',
	AX: 'Åland Islands',
	AL: 'Albania',
	DZ: 'Algeria',
	AS: 'American Samoa',
	AD: 'Andorra',
	AO: 'Angola',
	AI: 'Anguilla',
	AQ: 'Antarctica',
	AG: 'Antigua and Barbuda',
	AR: 'Argentina',
	AM: 'Armenia',
	AW: 'Aruba',
	AU: 'Australia',
	AT: 'Austria',
	AZ: 'Azerbaijan',
	BS: 'Bahamas',
	BH: 'Bahrain',
	BD: 'Bangladesh',
	BB: 'Barbados',
	BY: 'Belarus',
	BE: 'Belgium',
	BZ: 'Belize',
	BJ: 'Benin',
	BM: 'Bermuda',
	BT: 'Bhutan',
	BO: 'Bolivia, Plurinational State of',
	BO: 'Bolivia',
	BQ: 'Bonaire, Sint Eustatius and Saba',
	BA: 'Bosnia and Herzegovina',
	BW: 'Botswana',
	BV: 'Bouvet Island',
	BR: 'Brazil',
	IO: 'British Indian Ocean Territory',
	BN: 'Brunei Darussalam',
	BN: 'Brunei',
	BG: 'Bulgaria',
	BF: 'Burkina Faso',
	MM: 'Burma',
	BI: 'Burundi',
	KH: 'Cambodia',
	CM: 'Cameroon',
	CA: 'Canada',
	CV: 'Cape Verde',
	KY: 'Cayman Islands',
	CF: 'Central African Republic',
	TD: 'Chad',
	CL: 'Chile',
	CN: 'China',
	CX: 'Christmas Island',
	CC: 'Cocos (Keeling) Islands',
	CO: 'Colombia',
	KM: 'Comoros',
	CD: 'Congo, the Democratic Republic of the',
	CG: 'Congo',
	CK: 'Cook Islands',
	CR: 'Costa Rica',
	CI: "Côte d'Ivoire",
	HR: 'Croatia',
	CU: 'Cuba',
	CW: 'Curaçao',
	CY: 'Cyprus',
	CZ: 'Czech Republic',
	DK: 'Denmark',
	DJ: 'Djibouti',
	DM: 'Dominica',
	DO: 'Dominican Republic',
	EC: 'Ecuador',
	EG: 'Egypt',
	SV: 'El Salvador',
	GQ: 'Equatorial Guinea',
	ER: 'Eritrea',
	EE: 'Estonia',
	ET: 'Ethiopia',
	FK: 'Falkland Islands (Malvinas)',
	FO: 'Faroe Islands',
	FJ: 'Fiji',
	FI: 'Finland',
	FR: 'France',
	GF: 'French Guiana',
	PF: 'French Polynesia',
	TF: 'French Southern Territories',
	GA: 'Gabon',
	GM: 'Gambia',
	GE: 'Georgia',
	DE: 'Germany',
	GH: 'Ghana',
	GI: 'Gibraltar',
	GR: 'Greece',
	GL: 'Greenland',
	GD: 'Grenada',
	GP: 'Guadeloupe',
	GU: 'Guam',
	GT: 'Guatemala',
	GG: 'Guernsey',
	GW: 'Guinea-Bissau',
	GN: 'Guinea',
	GY: 'Guyana',
	HT: 'Haiti',
	HM: 'Heard Island and McDonald Islands',
	VA: 'Holy See (Vatican City State)',
	HN: 'Honduras',
	HK: 'Hong Kong',
	HU: 'Hungary',
	IS: 'Iceland',
	IN: 'India',
	ID: 'Indonesia',
	IR: 'Iran, Islamic Republic of',
	IQ: 'Iraq',
	IE: 'Ireland',
	IM: 'Isle of Man',
	IL: 'Israel',
	IT: 'Italy',
	CI: 'Ivory Coast',
	JM: 'Jamaica',
	JP: 'Japan',
	JE: 'Jersey',
	JO: 'Jordan',
	KZ: 'Kazakhstan',
	KE: 'Kenya',
	KI: 'Kiribati',
	KP: "Korea, Democratic People's Republic of",
	KR: 'Korea, Republic of',
	XK: 'Kosovo',
	KW: 'Kuwait',
	KG: 'Kyrgyzstan',
	LA: "Lao People's Democratic Republic",
	LV: 'Latvia',
	LB: 'Lebanon',
	LS: 'Lesotho',
	LR: 'Liberia',
	LY: 'Libya',
	LY: 'Libyan Arab Jamahiriya',
	LI: 'Liechtenstein',
	LT: 'Lithuania',
	LU: 'Luxembourg',
	MO: 'Macao',
	MK: 'Macedonia, the former Yugoslav Republic of',
	MG: 'Madagascar',
	MW: 'Malawi',
	MY: 'Malaysia',
	MV: 'Maldives',
	ML: 'Mali',
	MT: 'Malta',
	MH: 'Marshall Islands',
	MQ: 'Martinique',
	MR: 'Mauritania',
	MU: 'Mauritius',
	YT: 'Mayotte',
	MX: 'Mexico',
	FM: 'Micronesia, Federated States of',
	MD: 'Moldova, Republic of',
	MC: 'Monaco',
	MN: 'Mongolia',
	ME: 'Montenegro',
	MS: 'Montserrat',
	MA: 'Morocco',
	MZ: 'Mozambique',
	MM: 'Myanmar',
	NA: 'Namibia',
	NR: 'Nauru',
	NP: 'Nepal',
	AN: 'Netherlands Antilles',
	NL: 'Netherlands',
	NC: 'New Caledonia',
	NZ: 'New Zealand',
	NI: 'Nicaragua',
	NE: 'Niger',
	NG: 'Nigeria',
	NU: 'Niue',
	NF: 'Norfolk Island',
	MP: 'Northern Mariana Islands',
	NO: 'Norway',
	OM: 'Oman',
	PK: 'Pakistan',
	PW: 'Palau',
	PS: 'Palestinian Territory, Occupied',
	PA: 'Panama',
	PG: 'Papua New Guinea',
	PY: 'Paraguay',
	PE: 'Peru',
	PH: 'Philippines',
	PN: 'Pitcairn',
	PL: 'Poland',
	PT: 'Portugal',
	PR: 'Puerto Rico',
	QA: 'Qatar',
	RE: 'Réunion',
	RO: 'Romania',
	RU: 'Russia',
	RU: 'Russian Federation',
	RW: 'Rwanda',
	BL: 'Saint-Barthélemy',
	SH: 'Saint Helena, Ascension and Tristan da Cunha',
	KN: 'Saint Kitts and Nevis',
	LC: 'Saint Lucia',
	MF: 'Saint Martin (French part)',
	PM: 'Saint Pierre and Miquelon',
	VC: 'Saint Vincent & the Grenadines',
	VC: 'Saint Vincent and the Grenadines',
	WS: 'Samoa',
	SM: 'San Marino',
	ST: 'Sao Tome and Principe',
	SA: 'Saudi Arabia',
	SN: 'Senegal',
	RS: 'Serbia',
	SC: 'Seychelles',
	SL: 'Sierra Leone',
	SG: 'Singapore',
	SX: 'Sint Maarten (Dutch part)',
	SK: 'Slovakia',
	SI: 'Slovenia',
	SB: 'Solomon Islands',
	SO: 'Somalia',
	ZA: 'South Africa',
	GS: 'South Georgia and the South Sandwich Islands',
	KR: 'South Korea',
	SS: 'South Sudan',
	ES: 'Spain',
	LK: 'Sri Lanka',
	VC: 'St. Vincent and the Grenadines',
	SD: 'Sudan',
	SR: 'Suriname',
	SJ: 'Svalbard and Jan Mayen',
	SZ: 'Swaziland',
	SE: 'Sweden',
	CH: 'Switzerland',
	SY: 'Syrian Arab Republic',
	TW: 'Taiwan',
	TJ: 'Tajikistan',
	TZ: 'Tanzania, United Republic of',
	TH: 'Thailand',
	TL: 'Timor-Leste',
	TG: 'Togo',
	TK: 'Tokelau',
	TO: 'Tonga',
	TT: 'Trinidad and Tobago',
	TN: 'Tunisia',
	TR: 'Turkey',
	TM: 'Turkmenistan',
	TC: 'Turks and Caicos Islands',
	TV: 'Tuvalu',
	UG: 'Uganda',
	UA: 'Ukraine',
	AE: 'United Arab Emirates',
	GB: 'United Kingdom',
	UM: 'United States Minor Outlying Islands',
	US: 'United States',
	UY: 'Uruguay',
	UZ: 'Uzbekistan',
	VU: 'Vanuatu',
	VE: 'Venezuela, Bolivarian Republic of',
	VE: 'Venezuela',
	VN: 'Viet Nam',
	VN: 'Vietnam',
	VG: 'Virgin Islands, British',
	VI: 'Virgin Islands, U.S.',
	WF: 'Wallis and Futuna',
	EH: 'Western Sahara',
	YE: 'Yemen',
	ZM: 'Zambia',
	ZW: 'Zimbabwe'
};
