import * as d3 from 'd3';

export type KmI18n = {
	yAxisSurvivalProbability: string;
	tooltipGroup: string;
	tooltipTime: string;
	tooltipSurvivalProbability: string;
	tooltipLowerCI: string;
	tooltipUpperCI: string;
	legendUnspecified: string;
	legendOther: string;
	legendNoEntry: string;
	xAxisDays: string;
	xAxisMonths: string;
	xAxisYears: string;
};

export type GroupedKmRows = {
	groupedRows: Map<any, any[]>;
	groupedCensorRows: Map<any, any[]>;
	groupedDrawRows: Map<any, any[]>;
	groupedDrawCensorRows: Map<any, any[]>;
	groupHasConfidenceInterval: Map<any, boolean>;
	extent: [number, number];
};

export type KaplanMeierResult = GroupedKmRows & {
	vec: any[];
};

const DEFAULT_I18N_DE: KmI18n = {
	yAxisSurvivalProbability: 'Überlebenswahrscheinlichkeit',
	tooltipGroup: 'Gruppe',
	tooltipTime: 'Zeit',
	tooltipSurvivalProbability: 'Überlebenswahrscheinlichkeit',
	tooltipLowerCI: 'Unteres Konfidenzintervall',
	tooltipUpperCI: 'Oberes Konfidenzintervall',
	legendUnspecified: 'Unspezifiziert',
	legendOther: 'Sonstige',
	legendNoEntry: 'Ohne Eintrag',
	xAxisDays: 'Tage',
	xAxisMonths: 'Monate',
	xAxisYears: 'Jahre'
};

/**
 * Localize well-known group labels that are generated by preprocessing.
 * Keeps raw labels for numeric stages etc.
 */
function localizeGroupLabel(label: any, I18N: KmI18n): string {
	const s = (label ?? '').toString();
	if (s === '0') return I18N.legendUnspecified;
	// German raw buckets coming from preprocessing
	if (s === 'Sonstige') return I18N.legendOther;
	if (s === 'Ohne Eintrag') return I18N.legendNoEntry;
	return s;
}

export function KaplanMeier(inputvec: any[], groupvec: any[], selectedConfidenceType: string) {
	return KaplanMeierWithGrouping(inputvec, groupvec, selectedConfidenceType).vec;
}

export function KaplanMeierWithGrouping(
	inputvec: any[],
	groupvec: any[],
	selectedConfidenceType: string
): KaplanMeierResult {
	let Surv, Upper: number, Lower: number, N;
	let hsum, zw, ecount, ccount;
	let it = 0;
	const normalDistributionFactor = 1.96;
	const confidenceMode =
		selectedConfidenceType === '95% Konf.-Intervall'
			? 1
			: selectedConfidenceType === '95% Log Konf.-Intervall'
			? 2
			: selectedConfidenceType === '95% Loglog Konf-Intervall'
			? 3
			: 0;
	const shouldTrackConfidence = confidenceMode !== 0;

	// Length of object vector plus starting points for each group
	let vec = new Array(inputvec.length + groupvec.length);
	const groupedInput = new Map<any, any[]>();
	const groupedRows = new Map<any, any[]>();
	const groupedCensorRows = new Map<any, any[]>();
	const groupedDrawRows = new Map<any, any[]>();
	const groupedDrawCensorRows = new Map<any, any[]>();
	const groupHasConfidenceInterval = new Map<any, boolean>();
	let minTime = Infinity;
	let maxTime = -Infinity;

	for (let i = 0; i < inputvec.length; ++i) {
		const entry = inputvec[i];
		const groupEntries = groupedInput.get(entry.groupe);
		if (groupEntries) {
			groupEntries.push(entry);
		} else {
			groupedInput.set(entry.groupe, [entry]);
		}
	}

	for (let groupIndex = 0; groupIndex < groupvec.length; ++groupIndex) {
		const groupname = groupvec[groupIndex];
		const vect = groupedInput.get(groupname) || [];
		const groupRows = new Array(vect.length + 1);
		const censorRows: any[] = [];
		groupedRows.set(groupname, groupRows);
		groupedCensorRows.set(groupname, censorRows);
		groupHasConfidenceInterval.set(groupname, false);
		N = vect.length;

		// Starting point, neither censored nor with event
		let rowIndex = 0;
		let kmRow = {
			time: 0,
			event: 2,
			group: groupname,
			surv: 1,
			upper: 1,
			lower: 1,
			n: N,
			nevent: 0,
			ncensor: 0,
			tumorID: vect[0]?.tumorID || ''
		};
		vec[it] = kmRow;
		groupRows[rowIndex++] = kmRow;
		minTime = 0;
		if (maxTime < 0) maxTime = 0;
		++it;
		hsum = 0;
		ecount = 0;
		ccount = 0;

		for (let t = 0; t < vect.length; ++t, ++it) {
			const row = vect[t];
			const prev = vec[it - 1];
			if (row.status == 0) {
				--N;
				++ccount;
				kmRow = {
					time: row.dateDiff,
					event: 0,
					group: groupname,
					surv: prev.surv,
					upper: prev.upper,
					lower: prev.lower,
					n: N,
					nevent: ecount,
					ncensor: ccount,
					tumorID: row.tumorID
				};
				vec[it] = kmRow;
				groupRows[rowIndex++] = kmRow;
				censorRows.push(kmRow);
				if (kmRow.time < minTime) minTime = kmRow.time;
				if (kmRow.time > maxTime) maxTime = kmRow.time;
			} else {
				Surv = prev.surv * (1 - 1 / N);
				Upper = Surv;
				Lower = Surv;

				if (confidenceMode !== 0) {
					hsum += 1 / (N * (N - 1));
					if (confidenceMode === 1) {
						zw = normalDistributionFactor * Surv * Math.sqrt(hsum);
						Upper = Surv + zw;
						Lower = Surv - zw;
					} else if (confidenceMode === 2) {
						zw = normalDistributionFactor * Math.sqrt(hsum);
						Upper = Surv * Math.exp(zw);
						Lower = Surv * Math.exp(-1 * zw);
					} else if (confidenceMode === 3) {
						zw = normalDistributionFactor * (1 / Math.log(Surv)) * Math.sqrt(hsum);
						Upper = Math.pow(Surv, Math.exp(zw));
						Lower = Math.pow(Surv, Math.exp(-1 * zw));
					}
				}

				if (N == 1) {
					Upper = prev.upper;
					Lower = prev.lower;
				} else if (Upper > 1) {
					Upper = 1;
				} else if (Lower < 0) {
					Lower = 0;
				}

				++ecount;
				--N;
				kmRow = {
					time: row.dateDiff,
					event: 1,
					group: groupname,
					surv: Surv,
					upper: Upper,
					lower: Lower,
					n: N,
					nevent: ecount,
					ncensor: ccount,
					tumorID: row.tumorID
				};
				vec[it] = kmRow;
				groupRows[rowIndex++] = kmRow;
				if (
					shouldTrackConfidence &&
					!groupHasConfidenceInterval.get(groupname) &&
					Number.isFinite(Upper) &&
					Number.isFinite(Lower) &&
					(Upper !== Surv || Lower !== Surv)
				) {
					groupHasConfidenceInterval.set(groupname, true);
				}
				if (kmRow.time < minTime) minTime = kmRow.time;
				if (kmRow.time > maxTime) maxTime = kmRow.time;
			}
		}
		groupedDrawRows.set(groupname, compactStepRowsForDrawing(groupRows));
		groupedDrawCensorRows.set(groupname, compactCensorRowsForDrawing(censorRows));
	}

	return {
		vec,
		groupedRows,
		groupedCensorRows,
		groupedDrawRows,
		groupedDrawCensorRows,
		groupHasConfidenceInterval,
		extent: [minTime, maxTime]
	};
}

export function getDaysDivider(timetype: string) {
	switch (timetype) {
		case 'Monat':
			return 30.44;
		case 'Jahr':
			return 365;
		default:
			return 1;
	}
}

export function groupKmRowsByGroup(vec: any[], groupvec: any[]) {
	return groupKmRowsAndExtent(vec, groupvec).groupedRows;
}

export function groupKmRowsAndExtent(vec: any[], groupvec: any[]): GroupedKmRows {
	const groupedRows = new Map<any, any[]>();
	const groupedCensorRows = new Map<any, any[]>();
	const groupedDrawRows = new Map<any, any[]>();
	const groupedDrawCensorRows = new Map<any, any[]>();
	const groupHasConfidenceInterval = new Map<any, boolean>();
	let minTime = Infinity;
	let maxTime = -Infinity;

	for (let i = 0; i < groupvec.length; ++i) {
		groupedRows.set(groupvec[i], []);
		groupedCensorRows.set(groupvec[i], []);
		groupHasConfidenceInterval.set(groupvec[i], false);
	}

	for (let i = 0; i < vec.length; ++i) {
		const entry = vec[i];
		const groupRows = groupedRows.get(entry.group);
		if (groupRows) {
			groupRows.push(entry);
		} else {
			groupedRows.set(entry.group, [entry]);
		}
		if (entry.event === 0) {
			const censorRows = groupedCensorRows.get(entry.group);
			if (censorRows) {
				censorRows.push(entry);
			} else {
				groupedCensorRows.set(entry.group, [entry]);
			}
		}
		if (
			!groupHasConfidenceInterval.get(entry.group) &&
			Number.isFinite(entry.upper) &&
			Number.isFinite(entry.lower) &&
			(entry.upper !== entry.surv || entry.lower !== entry.surv)
		) {
			groupHasConfidenceInterval.set(entry.group, true);
		}
		if (entry.time < minTime) minTime = entry.time;
		if (entry.time > maxTime) maxTime = entry.time;
	}

	for (let i = 0; i < groupvec.length; ++i) {
		const groupname = groupvec[i];
		groupedDrawRows.set(groupname, compactStepRowsForDrawing(groupedRows.get(groupname) || []));
		groupedDrawCensorRows.set(
			groupname,
			compactCensorRowsForDrawing(groupedCensorRows.get(groupname) || [])
		);
	}

	return {
		groupedRows,
		groupedCensorRows,
		groupedDrawRows,
		groupedDrawCensorRows,
		groupHasConfidenceInterval,
		extent: [minTime, maxTime] as [number, number]
	};
}

export function getTimeExtent(vec: any[]): [number, number] {
	let minTime = Infinity;
	let maxTime = -Infinity;
	for (let i = 0; i < vec.length; ++i) {
		const time = vec[i].time;
		if (time < minTime) minTime = time;
		if (time > maxTime) maxTime = time;
	}
	return [minTime, maxTime];
}

export function InitSvg(
	gvec: any[],
	vec: any[],
	timetype: string,
	stratificationType: string,
	currentWidth: number,
	col: string[],
	leftSlider: number,
	rightSlider: number,
	i18n?: Partial<KmI18n>,
	rawTimeExtent?: [number, number],
	layout?: { width: number; height: number; compact: boolean }
) {
	const I18N: KmI18n = { ...DEFAULT_I18N_DE, ...(i18n || {}) };
	const compact = layout?.compact ?? false;
	//Hier erstmal nur zwei Gruppen (UICC z.B. - mehrere werden benötigt)
	var margin = compact
			? { top: 6, right: 16, bottom: 24, left: 38 }
			: { top: 10, right: 40, bottom: 30, left: 50 },
		width = Math.max(160, (layout?.width ?? currentWidth) - margin.left - margin.right),
		height = Math.max(120, (layout?.height ?? 690) - margin.top - margin.bottom);

	// append the svg object to the body of the page
	var svg = d3
		.select('#Plot')
		.append('svg')
		.attr('width', width + margin.left + margin.right)
		.attr('height', height + margin.top + margin.bottom)
		.style('font-size', compact ? '9px' : null)
		.append('g')
		.attr('transform', 'translate(' + margin.left + ',' + margin.top + ')');

	const daysDivider = getDaysDivider(timetype);

	const xExtent = rawTimeExtent
		? [rawTimeExtent[0] / daysDivider, rawTimeExtent[1] / daysDivider]
		: (d3.extent(
				vec.map((d: any) => d.time / daysDivider).filter((value: any) => typeof value === 'number')
		  ) as [number, number]);

	// Verwende die Slider-Grenzen als Min- und Max-Werte für die x-Achse
	const xMin = leftSlider / daysDivider;
	const xMax = rightSlider / daysDivider;

	// Verhindere, dass die x-Achse über die Slider-Grenzen hinausgeht
	const xDomainMin = Math.max(xMin, xExtent[0]);
	const xDomainMax = Math.min(xMax, xExtent[1]);

	// Definiere die x-Skala unter Verwendung der Ausdehnung
	const x = d3.scaleLinear().domain([xDomainMin, xDomainMax]).range([0, width]);

	svg
		.append('g')
		.attr('transform', 'translate(0,' + height + ')')
		.call(d3.axisBottom(x));

	// Füge die Monatsbeschriftung am Anfang der x-Achse hinzu
	svg
		.append('text')
		.attr('x', width / 2)
		.attr('y', height + margin.top + 20) // Passe die Position nach Bedarf an
		.attr('text-anchor', 'middle')
		.text(
			timetype === 'Tag'
				? I18N.xAxisDays
				: timetype === 'Monat'
				? I18N.xAxisMonths
				: timetype === 'Jahr'
				? I18N.xAxisYears
				: timetype
		);

	var y = d3.scaleLinear().domain([0, 1]).range([height, 0]);

	svg.append('g').call(d3.axisLeft(y));

	// Beschriftung für die y-Achse
	// Beschriftung für die y-Achse
	svg
		.append('text')
		.attr('transform', 'rotate(-90)')
		.attr('x', 0 - height / 2)
		.attr('y', 0 - margin.left) // Erhöhe den y-Wert für mehr Platz
		.attr('dy', '1em')
		.style('text-anchor', 'middle')
		.text(I18N.yAxisSurvivalProbability);

	var legendWidth = compact ? 116 : 160;
	var legendHeight = compact ? 18 : 30;
	const legendRowHeight = compact ? 13 : 20;

	if (stratificationType !== 'none' && stratificationType !== 'Keine Stratifikation') {
		// Erstelle das legendData Array basierend auf gvec
		var legendData = gvec.map((groupname: string | number, index: number) => {
			const label = localizeGroupLabel(groupname, I18N);
			legendHeight = legendHeight + legendRowHeight;
			return { label, color: col[index] };
		});

		var legendX = width - legendWidth; // Legende am rechten Rand
		var legendY = 10; // Abstand vom oberen Rand

		// Erstellen Sie eine Gruppe für die Legende
		var legend = svg.append('g').attr('transform', 'translate(' + legendX + ',' + legendY + ')');

		// Hinzufügen eines Hintergrunds für die Legende
		legend
			.append('rect')
			.attr('width', legendWidth)
			.attr('height', legendHeight)
			.attr('fill', 'white')
			.attr('opacity', 0.7);

		// Hinzufügen eines kleinen weißen Rechtecks oben rechts in der Legende
		legend
			.append('rect')
			.attr('x', legendWidth - (compact ? 18 : 30))
			.attr('y', compact ? 3 : 5)
			.attr('width', compact ? 12 : 20)
			.attr('height', compact ? 6 : 10)
			.attr('fill', 'white');

		// Hinzufügen von Farbkreisen und Beschriftungen für die Legende
		legend
			.selectAll('.legend-circle')
			.data(legendData)
			.enter()
			.append('circle')
			.attr('cx', compact ? 8 : 15)
			.attr('cy', (d, i) => (compact ? 14 : 25) + i * legendRowHeight)
			.attr('r', compact ? 3 : 5)
			.attr('fill', (d: any) => d.color);

		legend
			.selectAll('.legend-label')
			.data(legendData)
			.enter()
			.append('text')
			.attr('x', compact ? 14 : 25)
			.attr('y', function (d, i) {
				return (compact ? 14 : 25) + i * legendRowHeight;
			})
			.attr('dy', '0.32em')
			.text((d: any) => d.label)
			.attr('font-size', compact ? '9px' : '12px');
	}
	return { x, y, svg };
}

export function dsurv(
	groupname: string,
	color = 0,
	vec: any[],
	svg: d3.Selection<SVGGElement, unknown, HTMLElement, any>,
	x: d3.ScaleLinear<number, number>,
	y: d3.ScaleLinear<number, number>,
	col: string[],
	leftSlider: number, // LeftSlider direkt in Tagen
	selectedTimeType: string, // Zeittyp (z. B. Monat, Jahr)
	i18n?: Partial<KmI18n>,
	groupedVect?: any[],
	groupedCensorRows?: any[],
	hasConfidenceIntervalForGroup?: boolean,
	groupedDrawRows?: any[],
	groupedDrawCensorRows?: any[]
) {
	const I18N: KmI18n = { ...DEFAULT_I18N_DE, ...(i18n || {}) };
	const adjustedLeftSlider = leftSlider;
	const daysDivider = getDaysDivider(selectedTimeType);
	const scaledTime = (time: number) => time / daysDivider;

	// Clipping-Path hinzufügen
	svg
		.append('defs')
		.append('clipPath')
		.attr('id', `clip-${groupname}`)
		.append('rect')
		.attr('x', x(scaledTime(adjustedLeftSlider))) // Clipping-Startpunkt
		.attr('y', 0)
		.attr('width', x.range()[1] - x(scaledTime(adjustedLeftSlider))) // Restliche Breite
		.attr('height', y.range()[0]); // Gesamte Diagrammhöhe

	// Filtere die Daten nur für Zeitpunkte ab `leftSlider`.
	// If the caller already grouped rows by group, only scan that group slice.
	const groupRows = groupedVect || vec.filter((d: { group: any }) => d.group === groupname);
	const startIndex = lowerBoundTime(groupRows, adjustedLeftSlider);
	const filteredVect = startIndex === 0 ? groupRows : groupRows.slice(startIndex);
	const censorStartIndex = groupedCensorRows
		? lowerBoundTime(groupedCensorRows, adjustedLeftSlider)
		: 0;
	const filteredCensorRows = groupedCensorRows
		? censorStartIndex === 0
			? groupedCensorRows
			: groupedCensorRows.slice(censorStartIndex)
		: filteredVect.filter((d: { event: number }) => d.event === 0);
	const drawStartIndex = groupedDrawRows ? lowerBoundTime(groupedDrawRows, adjustedLeftSlider) : 0;
	const drawVect = groupedDrawRows
		? drawStartIndex === 0
			? groupedDrawRows
			: groupedDrawRows.slice(drawStartIndex)
		: compactStepRowsForDrawing(filteredVect);
	const drawCensorStartIndex = groupedDrawCensorRows
		? lowerBoundTime(groupedDrawCensorRows, adjustedLeftSlider)
		: 0;
	const drawCensorRows = groupedDrawCensorRows
		? drawCensorStartIndex === 0
			? groupedDrawCensorRows
			: groupedDrawCensorRows.slice(drawCensorStartIndex)
		: compactCensorRowsForDrawing(filteredCensorRows);

	const tooltip = document.getElementById('tooltip');
	const groupLabel = localizeGroupLabel(groupname, I18N);
	const hasConfidenceInterval =
		hasConfidenceIntervalForGroup ??
		filteredVect.some(
			(d: any) =>
				Number.isFinite(d.upper) &&
				Number.isFinite(d.lower) &&
				(d.upper !== d.surv || d.lower !== d.surv)
		);
	const tooltipHtml = (dataPoint: any) => {
		const roundedX = scaledTime(dataPoint.time).toFixed(2);
		const roundedY = dataPoint.surv.toFixed(2);
		const lines = [
			`${I18N.tooltipGroup}: ${groupLabel}`,
			`${I18N.tooltipTime}: ${roundedX}`,
			`${I18N.tooltipSurvivalProbability}: ${roundedY}`
		];

		if (hasConfidenceInterval) {
			lines.push(
				`${I18N.tooltipLowerCI}: ${dataPoint.lower.toFixed(2)}`,
				`${I18N.tooltipUpperCI}: ${dataPoint.upper.toFixed(2)}`
			);
		}

		return lines.join('<br>');
	};

	// Zeichne das obere Konfidenzintervall
	if (hasConfidenceInterval) {
		svg
			.append('path')
			.datum(drawVect)
			.attr('fill', 'none')
			.attr('stroke', col[color])
			.style('stroke-dasharray', '3,3')
			.attr('stroke-width', 1.5)
			.attr('clip-path', `url(#clip-${groupname})`) // Clipping anwenden
			.attr(
				'd',
				d3
					.line()
					.x((d: any) => x(scaledTime(d.time)))
					.y((d: any) => y(d.upper))
					.curve(d3.curveStepAfter)
			);

		// Zeichne das untere Konfidenzintervall
		svg
			.append('path')
			.datum(drawVect)
			.attr('fill', 'none')
			.attr('stroke', col[color])
			.style('stroke-dasharray', '3,3')
			.attr('stroke-width', 1.5)
			.attr('clip-path', `url(#clip-${groupname})`) // Clipping anwenden
			.attr(
				'd',
				d3
					.line()
					.x((d: any) => x(scaledTime(d.time)))
					.y((d: any) => y(d.lower))
					.curve(d3.curveStepAfter)
			);
	}

	// Zeichne die Kaplan-Meier-Kurve
	svg
		.append('path')
		.datum(drawVect)
		.attr('fill', 'none')
		.attr('stroke', col[color])
		.attr('stroke-width', 1.5)
		.attr('clip-path', `url(#clip-${groupname})`) // Clipping anwenden
		.attr(
			'd',
			d3
				.line()
				.x((d: any) => x(scaledTime(d.time)))
				.y((d: any) => y(d.surv))
				.curve(d3.curveStepAfter)
		)
		.on('mouseover', function (event: any, d: any) {
			const [mouseX, mouseY] = d3.pointer(event);
			const closestDataPoint = findClosestDataPointBisect(filteredVect, mouseX, x, scaledTime);

			if (closestDataPoint) {
				if (tooltip) {
					tooltip.style.display = 'block';
					tooltip.innerHTML = tooltipHtml(closestDataPoint);
					tooltip.style.left = mouseX - tooltip.offsetWidth / 2 + 'px';
					tooltip.style.top = mouseY - 20 + 'px';
				}
			}
		})
		.on('mouseout', function () {
			if (tooltip) {
				tooltip.style.display = 'none';
			}
		});

	// Zensuren markieren
	svg
		.selectAll('wth')
		.data(drawCensorRows)
		.join('line')
		.attr('stroke', col[color])
		.attr('x1', (d: { time: any }) => x(scaledTime(d.time)))
		.attr('x2', (d: { time: any }) => x(scaledTime(d.time)))
		.attr('y1', (d: { surv: number }) => y(d.surv + 0.01))
		.attr('y2', (d: { surv: number }) => y(d.surv - 0.01))
		.attr('clip-path', `url(#clip-${groupname})`) // Clipping anwenden
		.on(
			'mouseover',
			function (
				event: { pageX: number; pageY: number },
				d: { time: number; surv: number; upper: number; lower: number }
			) {
				const [mouseX, mouseY] = d3.pointer(event);
				if (tooltip) {
					tooltip.style.display = 'block';
					tooltip.innerHTML = tooltipHtml(d);
					tooltip.style.left = mouseX - tooltip.offsetWidth / 2 + 'px';
					tooltip.style.top = mouseY - 20 + 'px';
				}
			}
		)
		.on('mouseout', function () {
			if (tooltip) {
				tooltip.style.display = 'none';
			}
		});
}

export function compactStepRowsForDrawing(rows: any[]): any[] {
	if (rows.length < 3) return rows;

	const compacted: any[] = [];
	let bucketStart = 0;

	for (let i = 1; i <= rows.length; ++i) {
		if (i < rows.length && rows[i].time === rows[bucketStart].time) continue;

		compacted.push(rows[bucketStart]);
		if (i - 1 !== bucketStart) {
			compacted.push(rows[i - 1]);
		}
		bucketStart = i;
	}

	return compacted.length === rows.length ? rows : compacted;
}

export function compactCensorRowsForDrawing(rows: any[]): any[] {
	if (rows.length < 2) return rows;

	const compacted: any[] = [];
	let previous: any;
	for (let i = 0; i < rows.length; ++i) {
		const row = rows[i];
		if (previous && row.time === previous.time && row.surv === previous.surv) continue;
		compacted.push(row);
		previous = row;
	}

	return compacted.length === rows.length ? rows : compacted;
}

function lowerBoundTime(data: any[], time: number): number {
	let lo = 0;
	let hi = data.length;
	while (lo < hi) {
		const mid = (lo + hi) >> 1;
		if (data[mid].time < time) {
			lo = mid + 1;
		} else {
			hi = mid;
		}
	}
	return lo;
}

export function findClosestDataPointLinear(
	data: any[],
	mouseX: number,
	x: (arg0: any) => number,
	scaleTime: (time: number) => number
): any | null {
	let closestPoint: any | null = null;
	let closestDistance = Infinity;

	data.forEach((point: any) => {
		const xValue = x(scaleTime(point.time));
		const distance = Math.abs(xValue - mouseX);

		if (distance < closestDistance) {
			closestPoint = point;
			closestDistance = distance;
		}
	});

	return closestPoint;
}

export function findClosestDataPointBisect(
	data: any[],
	mouseX: number,
	x: (arg0: any) => number,
	scaleTime: (time: number) => number
): any | null {
	if (!data.length) return null;

	let lo = 0;
	let hi = data.length;
	while (lo < hi) {
		const mid = (lo + hi) >> 1;
		if (x(scaleTime(data[mid].time)) < mouseX) {
			lo = mid + 1;
		} else {
			hi = mid;
		}
	}

	const firstIndexForPixel = (index: number) => {
		const pixel = x(scaleTime(data[index].time));
		while (index > 0 && x(scaleTime(data[index - 1].time)) === pixel) {
			--index;
		}
		return index;
	};

	if (lo <= 0) return data[0];
	if (lo >= data.length) return data[firstIndexForPixel(data.length - 1)];

	const leftIndex = firstIndexForPixel(lo - 1);
	const rightIndex = firstIndexForPixel(lo);
	const leftDistance = Math.abs(x(scaleTime(data[leftIndex].time)) - mouseX);
	const rightDistance = Math.abs(x(scaleTime(data[rightIndex].time)) - mouseX);

	return rightDistance < leftDistance ? data[rightIndex] : data[leftIndex];
}
