import { Pat } from './pat.model';
import * as d3 from 'd3';

export type KmI18n = {
  yAxisSurvivalProbability: string;
  tooltipGroup: string;
  tooltipTime: string;
  tooltipSurvivalProbability: string;
  tooltipLowerCI: string;
  tooltipUpperCI: string;
  legendUnspecified: string;
  legendOther: string;
  legendNoEntry: string;
  xAxisDays: string;
  xAxisMonths: string;
  xAxisYears: string;
};

const DEFAULT_I18N_DE: KmI18n = {
  yAxisSurvivalProbability: "Überlebenswahrscheinlichkeit",
  tooltipGroup: "Gruppe",
  tooltipTime: "Zeit",
  tooltipSurvivalProbability: "Überlebenswahrscheinlichkeit",
  tooltipLowerCI: "Unteres Konfidenzintervall",
  tooltipUpperCI: "Oberes Konfidenzintervall",
  legendUnspecified: "Unspezifiziert",
  legendOther: "Sonstige",
  legendNoEntry: "Ohne Eintrag",
  xAxisDays: "Tage",
  xAxisMonths: "Monate",
  xAxisYears: "Jahre",
};

/**
 * Localize well-known group labels that are generated by preprocessing.
 * Keeps raw labels for numeric stages etc.
 */
function localizeGroupLabel(label: any, I18N: KmI18n): string {
  const s = (label ?? "").toString();
  if (s === "0") return I18N.legendUnspecified;
  // German raw buckets coming from preprocessing
  if (s === "Sonstige") return I18N.legendOther;
  if (s === "Ohne Eintrag") return I18N.legendNoEntry;
  return s;
}

export function KaplanMeier(inputvec: any[], groupvec: any[], selectedConfidenceType: string) {

  let Surv, Upper: number, Lower: number, N;
  let hsum, zw, ecount, ccount;
  let it = 0;

  // Length of object vector plus starting points for each group
  let vec = new Array(inputvec.length + groupvec.length);

  groupvec.forEach((groupname: number) => {
    // filter for only group
    let vect = inputvec.filter(function (d: { groupe: any; }) { return d.groupe == groupname });
    N = vect.length;

    // Starting point, neither censored nor with event
    vec[it] = new Pat(
      0, 2, groupname, 1, 1, 1, N, 0, 0, vect[0]?.tumorID || "" // tumorID moved to the last parameter
    );
    ++it;
    hsum = 0;
    ecount = 0;
    ccount = 0;

    for (let t = 0; t < vect.length; ++t, ++it) {
      if (vect[t].status == 0) {
        --N;
        ++ccount;
        vec[it] = new Pat(
          vect[t].dateDiff, 0, groupname,
          vec[it - 1].surv, vec[it - 1].upper, vec[it - 1].lower, N, ecount, ccount, vect[t].tumorID // tumorID moved to the last parameter
        );
      } else {
        Surv = vec[it - 1].surv * (1 - 1 / N);
        hsum += 1 / ((N) * (N - 1));
        Upper = Surv;
        Lower = Surv;

        const normalDistributionFactor = 1.96;
        // simple confidence interval
        if (selectedConfidenceType == '95% Konf.-Intervall') {
          zw = normalDistributionFactor * Surv * Math.sqrt(hsum);
          Upper = Surv + zw;
          Lower = Surv - zw;
        }
        // Log confidence intervals
        if (selectedConfidenceType == '95% Log Konf.-Intervall') {
          zw = normalDistributionFactor * Math.sqrt(hsum);
          Upper = Surv * Math.exp(zw);
          Lower = Surv * Math.exp(-1 * zw);
        }
        // Log-log confidence intervals
        if (selectedConfidenceType == '95% Loglog Konf-Intervall') {
          zw = normalDistributionFactor * (1 / Math.log(Surv)) * Math.sqrt(hsum);
          Upper = Math.pow(Surv, Math.exp(zw));
          Lower = Math.pow(Surv, Math.exp(-1 * zw));
        }

        if (N == 1) {
          Upper = vec[it - 1].upper;
          Lower = vec[it - 1].lower;
        } else if (Upper > 1) {
          Upper = 1;
        } else if (Lower < 0) {
          Lower = 0;
        }

        ++ecount;
        --N;
        vec[it] = new Pat(
          vect[t].dateDiff, 1, groupname,
          Surv, Upper, Lower, N, ecount, ccount, vect[t].tumorID // tumorID moved to the last parameter
        );
      }
    }
  });

  return vec;
}

export function InitSvg(gvec: any[], vec: any[], timetype: string, stratificationType: string, currentWidth: number, col: string[], leftSlider: number, rightSlider: number, i18n?: Partial<KmI18n>) {  
    const I18N: KmI18n = { ...DEFAULT_I18N_DE, ...(i18n || {}) };
//Hier erstmal nur zwei Gruppen (UICC z.B. - mehrere werden benötigt)
  var margin = { top: 10, right: 40, bottom: 30, left: 50 },
    width = currentWidth - margin.left - margin.right,
    height = 690 - margin.top - margin.bottom;

  // append the svg object to the body of the page
  var svg = d3.select("#Plot")
    .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
    .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  var daysDivider = 1;

  switch (timetype) {
    case "Monat":
      daysDivider = 30.44
      break;
    case "Jahr":
      daysDivider = 365
      break;
    default:
      break;
  }
/*
  vec.forEach((pat: { time: number }) => {
    if (pat.time >= leftSlider && pat.time <= rightSlider) {
      pat.time = pat.time / daysDivider;
    }
  });*/

  vec.forEach((pat: { time: number; }) => pat.time = pat.time / daysDivider)


// Filtere alle Elemente im Array, bei denen "time" definiert ist, und konvertiere sie in eine number[]
// Clean the data by filtering out undefined and non-numeric values
const cleanedData = vec.map((d: any) => d.time).filter((value: any) => typeof value === 'number');

// Calculate the extent using the cleaned data
const xExtent = d3.extent(cleanedData) as [number, number];

// Verwende die Slider-Grenzen als Min- und Max-Werte für die x-Achse
const xMin = leftSlider / daysDivider;
const xMax = rightSlider / daysDivider;

// Verhindere, dass die x-Achse über die Slider-Grenzen hinausgeht
const xDomainMin = Math.max(xMin, xExtent[0]);
const xDomainMax = Math.min(xMax, xExtent[1]);

// Definiere die x-Skala unter Verwendung der Ausdehnung
const x = d3.scaleLinear()
  .domain([xDomainMin, xDomainMax])
  .range([0, width]);




  svg.append("g")
    .attr("transform", "translate(0," + height + ")")
    .call(d3.axisBottom(x))

  // Füge die Monatsbeschriftung am Anfang der x-Achse hinzu
  svg.append("text")
    .attr("x", width / 2)
    .attr("y", height + margin.top + 20) // Passe die Position nach Bedarf an
    .attr("text-anchor", "middle")
    .text(
      timetype === "Tag" ? I18N.xAxisDays :
      timetype === "Monat" ? I18N.xAxisMonths :
      timetype === "Jahr" ? I18N.xAxisYears :
      timetype
    );

  var y = d3.scaleLinear()
    .domain([0, 1])
    .range([height, 0]);

  svg.append("g")
    .call(d3.axisLeft(y))

  // Beschriftung für die y-Achse
  // Beschriftung für die y-Achse
  svg.append("text")
    .attr("transform", "rotate(-90)")
    .attr("x", 0 - (height / 2))
    .attr("y", 0 - margin.left) // Erhöhe den y-Wert für mehr Platz
    .attr("dy", "1em")
    .style("text-anchor", "middle")
    .text(I18N.yAxisSurvivalProbability);

    var legendWidth = 160;
    var legendHeight = 30;

    if(stratificationType !== 'none' && stratificationType !== 'Keine Stratifikation'){
  // Erstelle das legendData Array basierend auf gvec
  var legendData = gvec.map((groupname: string | number, index: number) => {
    const label = localizeGroupLabel(groupname, I18N);
    legendHeight = legendHeight+ 20;
    return { label, color: col[index] };
  });


  var legendX = width - legendWidth; // Legende am rechten Rand
  var legendY = 10; // Abstand vom oberen Rand

  // Erstellen Sie eine Gruppe für die Legende
  var legend = svg.append("g")
    .attr("transform", "translate(" + legendX + "," + legendY + ")");

  // Hinzufügen eines Hintergrunds für die Legende
  legend.append("rect")
    .attr("width", legendWidth)
    .attr("height", legendHeight)
    .attr("fill", "white")
    .attr("opacity", 0.7);

  // Hinzufügen eines kleinen weißen Rechtecks oben rechts in der Legende
  legend.append("rect")
    .attr("x", legendWidth - 30)
    .attr("y", 5)
    .attr("width", 20)
    .attr("height", 10)
    .attr("fill", "white");

  // Hinzufügen von Farbkreisen und Beschriftungen für die Legende
  legend.selectAll(".legend-circle")
    .data(legendData)
    .enter().append("circle")
    .attr("cx", 15)
    .attr("cy", (d, i) => 25 + i * 20)
    .attr("r", 5)
    .attr("fill", (d: any) => d.color);

  legend.selectAll(".legend-label")
    .data(legendData)
    .enter().append("text")
    .attr("x", 25)
    .attr("y", function (d, i) { return 25 + i * 20; })
    .attr("dy", "0.32em")
    .text((d: any) => d.label)
    .attr("font-size", "12px");
}
  return { x, y, svg }
}

export function dsurv(
  groupname: string,
  color = 0,
  vec: any[],
  svg: d3.Selection<SVGGElement, unknown, HTMLElement, any>,
  x: d3.ScaleLinear<number, number>,
  y: d3.ScaleLinear<number, number>,
  col: string[],
  leftSlider: number, // LeftSlider direkt in Tagen
  selectedTimeType: string, // Zeittyp (z. B. Monat, Jahr)
  i18n?: Partial<KmI18n>
) {
  const I18N: KmI18n = { ...DEFAULT_I18N_DE, ...(i18n || {}) };
  console.log("LeftSlider (Tage):", leftSlider);

  // Verwende den `leftSlider` direkt, da er in Tagen übergeben wird
  const adjustedLeftSlider = leftSlider;

  // Clipping-Path hinzufügen
  svg.append("defs")
    .append("clipPath")
    .attr("id", `clip-${groupname}`)
    .append("rect")
    .attr("x", x(adjustedLeftSlider)) // Clipping-Startpunkt
    .attr("y", 0)
    .attr("width", x.range()[1] - x(adjustedLeftSlider)) // Restliche Breite
    .attr("height", y.range()[0]); // Gesamte Diagrammhöhe

  // Filtere die Daten nur für Zeitpunkte ab `leftSlider`
  const filteredVect = vec.filter((d: { group: any; time: number }) =>
    d.group === groupname && d.time >= adjustedLeftSlider
  );

  console.log("Filtered Data:", filteredVect);

  const tooltip = document.getElementById("tooltip");
  const groupLabel = localizeGroupLabel(groupname, I18N);
  const hasConfidenceInterval = filteredVect.some(
    (d: any) =>
      Number.isFinite(d.upper) &&
      Number.isFinite(d.lower) &&
      (d.upper !== d.surv || d.lower !== d.surv)
  );
  const tooltipHtml = (dataPoint: any) => {
    const roundedX = dataPoint.time.toFixed(2);
    const roundedY = dataPoint.surv.toFixed(2);
    const lines = [
      `${I18N.tooltipGroup}: ${groupLabel}`,
      `${I18N.tooltipTime}: ${roundedX}`,
      `${I18N.tooltipSurvivalProbability}: ${roundedY}`
    ];

    if (hasConfidenceInterval) {
      lines.push(
        `${I18N.tooltipLowerCI}: ${dataPoint.lower.toFixed(2)}`,
        `${I18N.tooltipUpperCI}: ${dataPoint.upper.toFixed(2)}`
      );
    }

    return lines.join("<br>");
  };

  // Zeichne das obere Konfidenzintervall
  if (hasConfidenceInterval) {
    svg.append("path")
      .datum(filteredVect)
      .attr("fill", "none")
      .attr("stroke", col[color])
      .style("stroke-dasharray", ("3,3"))
      .attr("stroke-width", 1.5)
      .attr("clip-path", `url(#clip-${groupname})`) // Clipping anwenden
      .attr("d", d3.line()
        .x((d: any) => x(d.time))
        .y((d: any) => y(d.upper))
        .curve(d3.curveStepAfter)
      );

    // Zeichne das untere Konfidenzintervall
    svg.append("path")
      .datum(filteredVect)
      .attr("fill", "none")
      .attr("stroke", col[color])
      .style("stroke-dasharray", ("3,3"))
      .attr("stroke-width", 1.5)
      .attr("clip-path", `url(#clip-${groupname})`) // Clipping anwenden
      .attr("d", d3.line()
        .x((d: any) => x(d.time))
        .y((d: any) => y(d.lower))
        .curve(d3.curveStepAfter)
      );
  }

  // Zeichne die Kaplan-Meier-Kurve
  svg.append("path")
    .datum(filteredVect)
    .attr("fill", "none")
    .attr("stroke", col[color])
    .attr("stroke-width", 1.5)
    .attr("clip-path", `url(#clip-${groupname})`) // Clipping anwenden
    .attr("d", d3.line()
      .x((d: any) => x(d.time))
      .y((d: any) => y(d.surv))
      .curve(d3.curveStepAfter)
    )
    .on("mouseover", function (event: any, d: any) {
      const [mouseX, mouseY] = d3.pointer(event);
      const closestDataPoint = findClosestDataPoint(filteredVect, mouseX, x);

      if (closestDataPoint) {
        if (tooltip) {
          tooltip.style.display = "block";
          tooltip.innerHTML = tooltipHtml(closestDataPoint);
          tooltip.style.left = (mouseX - tooltip.offsetWidth / 2) + "px";
          tooltip.style.top = (mouseY - 20) + "px";
        }
      }
    })
    .on("mouseout", function () {
      if (tooltip) {
        tooltip.style.display = "none";
      }
    });

  // Zensuren markieren
  svg.selectAll("wth")
    .data(filteredVect.filter((d: { event: number }) => d.event === 0))
    .join("line")
    .attr("stroke", col[color])
    .attr("x1", (d: { time: any }) => x(d.time))
    .attr("x2", (d: { time: any }) => x(d.time))
    .attr("y1", (d: { surv: number }) => y(d.surv + 0.01))
    .attr("y2", (d: { surv: number }) => y(d.surv - 0.01))
    .attr("clip-path", `url(#clip-${groupname})`) // Clipping anwenden
    .on("mouseover", function (event: { pageX: number; pageY: number }, d: { time: number; surv: number; upper: number; lower: number }) {
      const [mouseX, mouseY] = d3.pointer(event);
      if (tooltip) {
        tooltip.style.display = "block";
        tooltip.innerHTML = tooltipHtml(d);
        tooltip.style.left = (mouseX - tooltip.offsetWidth / 2) + "px";
        tooltip.style.top = (mouseY - 20) + "px";
      }
    })
    .on("mouseout", function () {
      if (tooltip) {
        tooltip.style.display = "none";
      }
    });
    console.log("LeftSlider (Tage):", leftSlider);
    console.log("Clipping X-Position:", x(leftSlider));
    console.log("Gefilterte Daten:", filteredVect);
  console.log("Ich bin durchgelaufen!" + groupname);
}



function findClosestDataPoint(data: Pat[], mouseX: number, x: (arg0: any) => number): Pat | null {
  let closestPoint: Pat | null = null;
  let closestDistance = Infinity;

  data.forEach((point: Pat) => {
    const xValue = x(point.time);
    const distance = Math.abs(xValue - mouseX);

    if (distance < closestDistance) {
      closestPoint = point;
      closestDistance = distance;
    }
  });

  return closestPoint;
}

