const { randomBytes } = require('node:crypto');
const { GraphQLError } = require('graphql');
const { parseClinicalFilter } = require('../accessControl');

const POLICY_VERSION = '2026-10-02';
const WRITE_OPTIONS = { writeConcern: { w: 'majority', j: true } };
const ID_PATTERN = /^[a-f0-9]{24}$/;
const TERMINAL = new Set(['SAVED', 'DOWNLOAD_STARTED', 'CANCELLED', 'FAILED']);
const FORMATS = { TABLE: 'CSV', CHART: 'PNG', FILTER: 'JSON' };
const error = (message, code = 'BAD_USER_INPUT') =>
	new GraphQLError(message, { extensions: { code } });
const unavailable = () => error('Export audit could not be persisted', 'SERVICE_UNAVAILABLE');

function actorFor(context) {
	const actor = context.security;
	if (!actor || actor.anonymous || !actor.userId || !actor.sub)
		throw error('Authentication required', 'UNAUTHENTICATED');
	return {
		userId: actor.userId,
		userRole: actor.role,
		anonymousDemo: false,
		actorSubject: actor.sub
	};
}

function text(value, name, max, optional = false) {
	if (optional && value == null) return null;
	if (
		typeof value !== 'string' ||
		!value.trim() ||
		value.length > max ||
		/[\u0000-\u001f\u007f]/.test(value)
	)
		throw error(`Invalid export ${name}`);
	return value.trim();
}

function selectionJson(value) {
	if (value == null) return null;
	if (typeof value !== 'string' || value.length > 250000) throw error('Invalid export selection');
	let parsed;
	try {
		parsed = JSON.parse(value);
	} catch {
		throw error('Invalid export selection');
	}
	if (!parsed || typeof parsed !== 'object') throw error('Invalid export selection');
	let nodes = 0;
	function visit(node, depth) {
		if (++nodes > 10000 || depth > 20) throw error('Invalid export selection');
		if (node && typeof node === 'object')
			Object.values(node).forEach((child) => visit(child, depth + 1));
	}
	visit(parsed, 0);
	return JSON.stringify(parsed);
}

const serializeFilter = (ast) => (ast ? JSON.stringify(ast) : null);

function auditInput(input, context) {
	if (!input || input.policyVersion !== POLICY_VERSION)
		throw error('Export handling confirmation is required');
	if (!Object.hasOwn(FORMATS, input.kind) || FORMATS[input.kind] !== input.format)
		throw error('Invalid export kind or format');
	if (typeof input.filterActive !== 'boolean') throw error('Invalid export filter state');
	const route = text(input.route, 'route', 512);
	if (!/^\/[A-Za-z0-9_./%~-]*$/.test(route)) throw error('Invalid export route');
	const stored = context.security?.user?.userFilter;
	const mandatory = parseClinicalFilter(
		Array.isArray(stored) ? stored[stored.length - 1] : stored,
		context
	);
	const requested = parseClinicalFilter(input.filter, context);
	const active = input.filterActive ? requested : null;
	const effective =
		mandatory && active ? { operand: 'AND', children: [mandatory, active] } : mandatory || active;
	return {
		route,
		title: text(input.title, 'title', 240),
		kind: input.kind,
		format: input.format,
		fileName: text(input.fileName, 'filename', 200),
		filterActive: input.filterActive,
		filter: serializeFilter(requested),
		mandatoryFilter: serializeFilter(mandatory),
		effectiveFilter: serializeFilter(effective),
		selection: selectionJson(input.selection),
		policyVersion: POLICY_VERSION,
		appVersion: text(input.appVersion, 'application version', 80),
		// Size, hash and selection describe browser-generated bytes, not a server-generated file.
		metadataSource: 'browser'
	};
}

function fileNameFor(value, format, id) {
	const stem =
		value
			.replace(/\.[^.]*$/, '')
			.replace(/[^\p{L}\p{N}._ -]/gu, '_')
			.replace(/^[. ]+|[. ]+$/g, '') || 'OVIS_Export';
	return `${stem.slice(0, 150)}_${id}.${format.toLowerCase()}`;
}

function ownerQuery(id, context) {
	if (typeof id !== 'string' || !ID_PATTERN.test(id)) throw error('Invalid export audit ID');
	const actor = actorFor(context);
	return {
		_id: id,
		userId: actor.userId,
		actorSubject: actor.actorSubject,
		anonymousDemo: actor.anonymousDemo
	};
}

async function owned(collection, query) {
	const row = await collection.findOne(query);
	if (!row) throw error('Export audit is not available to this account', 'FORBIDDEN');
	return row;
}

function artifact(input) {
	if (
		!Number.isSafeInteger(input.sizeBytes) ||
		input.sizeBytes < 0 ||
		input.sizeBytes > 10 * 1024 ** 3
	)
		throw error('Invalid export byte count');
	if (typeof input.sha256 !== 'string' || !/^[a-fA-F0-9]{64}$/.test(input.sha256))
		throw error('Invalid export SHA-256');
	if (
		input.rowCount != null &&
		(!Number.isInteger(input.rowCount) || input.rowCount < 0 || input.rowCount > 2147483647)
	)
		throw error('Invalid export row count');
	return {
		sizeBytes: input.sizeBytes,
		sha256: input.sha256.toLowerCase(),
		rowCount: input.rowCount ?? null
	};
}

const sameArtifact = (row, fields) =>
	Object.entries(fields).every(([key, value]) => row[key] === value);
const forApi = (row) => ({
	...row,
	id: row._id,
	createdAt: Number(row.createdAt),
	preparedAt: row.preparedAt == null ? null : Number(row.preparedAt),
	completedAt: row.completedAt == null ? null : Number(row.completedAt)
});

module.exports = {
	Mutation: {
		createExportAudit: async (_parent, { input }, context) => {
			const actor = actorFor(context);
			const fields = auditInput(input, context);
			const collection = context.db.collection(context.collections.exportAudit);
			for (let attempt = 0; attempt < 3; attempt++) {
				const id = randomBytes(12).toString('hex');
				const createdAt = new Date();
				const fileName = fileNameFor(fields.fileName, fields.format, id);
				try {
					const result = await collection.insertOne(
						{
							_id: id,
							schemaVersion: 1,
							...fields,
							...actor,
							fileName,
							createdAt,
							confirmedAt: createdAt,
							preparedAt: null,
							completedAt: null,
							sizeBytes: null,
							sha256: null,
							rowCount: null,
							status: 'CREATED'
						},
						WRITE_OPTIONS
					);
					if (!result.acknowledged) throw unavailable();
					return { id, fileName, createdAt: createdAt.getTime() };
				} catch (cause) {
					if (cause?.code === 11000) continue;
					throw unavailable();
				}
			}
			throw unavailable();
		},
		prepareExportAudit: async (_parent, input, context) => {
			const query = ownerQuery(input.id, context);
			const fields = artifact(input);
			const collection = context.db.collection(context.collections.exportAudit);
			let row = await owned(collection, query);
			if (row.status === 'PREPARED' && sameArtifact(row, fields)) return true;
			if (row.status !== 'CREATED') throw error('Export artifact is already sealed');
			const result = await collection.updateOne(
				{ ...query, status: 'CREATED' },
				{
					$set: { ...fields, status: 'PREPARED', preparedAt: new Date() }
				},
				WRITE_OPTIONS
			);
			if (!result.acknowledged) throw unavailable();
			if (result.matchedCount === 1) return true;
			row = await owned(collection, query);
			if (row.status === 'PREPARED' && sameArtifact(row, fields)) return true;
			throw error('Export artifact is already sealed');
		},
		completeExportAudit: async (_parent, { id, outcome }, context) => {
			const query = ownerQuery(id, context);
			if (!TERMINAL.has(outcome)) throw error('Invalid export outcome');
			const collection = context.db.collection(context.collections.exportAudit);
			let row = await owned(collection, query);
			if (row.status === outcome) return true;
			if (
				!['CREATED', 'PREPARED'].includes(row.status) ||
				(row.status !== 'PREPARED' && !['CANCELLED', 'FAILED'].includes(outcome))
			)
				throw error('Invalid export status transition');
			const result = await collection.updateOne(
				{ ...query, status: row.status },
				{
					$set: { status: outcome, completedAt: new Date() }
				},
				WRITE_OPTIONS
			);
			if (!result.acknowledged) throw unavailable();
			if (result.matchedCount === 1) return true;
			row = await owned(collection, query);
			if (row.status === outcome) return true;
			throw error('Invalid export status transition');
		}
	},
	Query: {
		getExportAudits: async (_parent, { search, offset = 0, limit = 50 }, context) => {
			const actor = actorFor(context);
			if (!['admin', 'super-admin'].includes(actor.userRole))
				throw error('Administrator permission required', 'FORBIDDEN');
			if (
				!Number.isInteger(offset) ||
				offset < 0 ||
				offset > 1000000 ||
				!Number.isInteger(limit) ||
				limit < 1 ||
				limit > 100
			)
				throw error('Invalid export audit page');
			if (
				search != null &&
				(typeof search !== 'string' || search.length > 200 || /[\u0000-\u001f\u007f]/.test(search))
			)
				throw error('Invalid export audit search');
			const term = search?.trim();
			const match = !term
				? {}
				: ID_PATTERN.test(term.toLowerCase())
				? { _id: term.toLowerCase() }
				: /^[a-fA-F0-9]{64}$/.test(term)
				? { sha256: term.toLowerCase() }
				: {
						$or: ['userId', 'fileName'].map((field) => ({
							[field]: { $regex: term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), $options: 'i' }
						}))
				  };
			const collection = context.db.collection(context.collections.exportAudit);
			const [total, rows] = await Promise.all([
				collection.countDocuments(match),
				collection.find(match).sort({ createdAt: -1, _id: -1 }).skip(offset).limit(limit).toArray()
			]);
			return { total, records: rows.map(forApi) };
		}
	}
};
